### ISSUE TITLE
Panel: panel-content should be shrinkable

### ISSUE THREAD

**Issue by nerder** [buildo/react-components#362] opened 2016-03-23 14:03 UTC
## description

`Panel` have a shrink rule that is opinionated and do not allow the user to customize the behaviour of `panel-content` this will end in some tricky workaround to avoid this. IMO is way better to fix this by our side and let the devs free to customize `panel-content`as they want.

## how to reproduce
This is the involved line of code :
 ```javascript
<FlexView className='panel-content' column grow shrink={false} style={{ position: 'relative' }}>
```

## specs
This is the proposed solution:
 ```javascript
<FlexView className='panel-content' column grow style={{ position: 'relative' }}>
```

## misc

About the solution proposed, leave the `shrink` as true (`flex: 1 1 auto`) will not change the behaviour in any ways, and the same result can always be reached adding a child `FlexView` with a `shrink: false` property, in the opposite way instead is very opinionated, and if we want for instance make the content scroll we have to do something like a small workaround (as proposed [here](http://missing) for instance)

**Comment by gabro** [comment] 2016-09-09 15:36
@FrancescoCioria is this still a concern?

**Comment by FrancescoCioria** [comment] 2016-09-13 08:47
no, duplicate of #414

**Closed by FrancescoCioria** 2016-09-13 08:47 UTC
Labels: defect
